#!/bin/sh -e

die() {
	echo >&2 "$(basename "$0"): error:" "$@"
	exit 1
}

# close stdin
exec 0<&-

# process parameters
cleanup='yes'

while [ $# -gt 0 ]; do
	case "$1" in
		-k|--keep)		unset cleanup; shift ;;
		-b|--bench)		bench='yes'; shift ;;
		-v|--verbose)	opt='-v'; shift ;;
		*)				die "unknown option \"$1\"" ;;
	esac
done

# set-up
cache_src=$(mktemp --suffix='.go' -p .)

trap 'rm -f "$cache_src"' ${cleanup:+EXIT} INT TERM QUIT HUP

# generate code and run tests
./gen-cache -k int -v int -n myCache -p main -o "$cache_src"
go test "$opt" ${bench:+-bench .}
